name: Auto Commit

on:
  push:
    branches:
      - main  # Lub inna nazwa gałęzi

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "twój_email@example.com"
          git config --global user.name "Twoje Imię"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automatyczny commit z GitHub Actions"
          git push origin main
