name: Auto Commit

on:
  push:
    branches:
      - main  # Lub inna nazwa gałęzi

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "andrew.mroz@gmail.com"
          git config --global user.name "Zimny65"

      - name: Commit changes
        run: |
          git add .
          git commit -m "GitHub Actions automatic commit"
          git push origin main
